In [1]:
import math
import torch
import gpytorch
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt

import GPE_ensemble as GPE

import os
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.model_selection import train_test_split
#from GPErks.gp.data.dataset import Dataset
from gpytorch.likelihoods import GaussianLikelihood
from gpytorch.means import LinearMean
from gpytorch.kernels import RBFKernel, ScaleKernel
from torchmetrics import MeanSquaredError, R2Score
#from GPErks.gp.experiment import GPExperiment
#from GPErks.train.emulator import GPEmulator
#from GPErks.perks.inference import Inference
#from GPErks.train.early_stop import NoEarlyStoppingCriterion
#from GPErks.train.early_stop import (
#    GLEarlyStoppingCriterion,
#    PQEarlyStoppingCriterion,
#    UPEarlyStoppingCriterion,
#)
#from GPErks.train.early_stop import PkEarlyStoppingCriterion



%matplotlib inline
%load_ext autoreload
%autoreload 2

# set logger and enforce reproducibility
#from GPErks.log.logger import get_logger
#from GPErks.utils.random import set_seed
#log = get_logger()
seed = 7
#set_seed(seed)
from time import process_time 
import scipy
from scipy.optimize import minimize

In [2]:
x_labels=pd.read_csv(r'/Users/pmzcwl/Library/CloudStorage/OneDrive-TheUniversityofNottingham/shared_simulations/EP_healthy/input/xlabels_EP.txt',delim_whitespace=True,header=None)

y_labels=pd.read_csv(r'/Users/pmzcwl/Library/CloudStorage/OneDrive-TheUniversityofNottingham/shared_simulations/EP_healthy/output/ylabels.txt',delim_whitespace=True,header=None)

y_labels

inputData_0 = pd.read_csv("/Users/pmzcwl/Library/CloudStorage/OneDrive-TheUniversityofNottingham/shared_simulations/EP_healthy/01/X_EP.txt",index_col=None,delim_whitespace=True,header=None).values
outputData_0 = pd.read_csv("/Users/pmzcwl/Library/CloudStorage/OneDrive-TheUniversityofNottingham/shared_simulations/EP_healthy/01/Y.txt",index_col=None,delim_whitespace=True,header=None).values

inputData_1 = pd.read_csv("/Users/pmzcwl/Library/CloudStorage/OneDrive-TheUniversityofNottingham/shared_simulations/EP_healthy/02/X_EP.txt",index_col=None,delim_whitespace=True,header=None).values
outputData_1 = pd.read_csv("/Users/pmzcwl/Library/CloudStorage/OneDrive-TheUniversityofNottingham/shared_simulations/EP_healthy/02/Y.txt",index_col=None,delim_whitespace=True,header=None).values

X0 = torch.tensor(inputData_0)
Y0 = torch.tensor(outputData_0)

X1 = torch.tensor(inputData_1)
Y1 = torch.tensor(outputData_1)



emulator_0 = GPE.ensemble(X0,Y0,mean_func="constant",training_iter=500)

0
Iter 1/500 - Loss: 1.373
Iter 2/500 - Loss: 1.337
Iter 3/500 - Loss: 1.298
Iter 4/500 - Loss: 1.256
Iter 5/500 - Loss: 1.212
Iter 6/500 - Loss: 1.166
Iter 7/500 - Loss: 1.118
Iter 8/500 - Loss: 1.068
Iter 9/500 - Loss: 1.017
Iter 10/500 - Loss: 0.965
Iter 11/500 - Loss: 0.913
Iter 12/500 - Loss: 0.860
Iter 13/500 - Loss: 0.807
Iter 14/500 - Loss: 0.755
Iter 15/500 - Loss: 0.703
Iter 16/500 - Loss: 0.651
Iter 17/500 - Loss: 0.600
Iter 18/500 - Loss: 0.549
Iter 19/500 - Loss: 0.499
Iter 20/500 - Loss: 0.450
Iter 21/500 - Loss: 0.401
Iter 22/500 - Loss: 0.352
Iter 23/500 - Loss: 0.305
Iter 24/500 - Loss: 0.258
Iter 25/500 - Loss: 0.211
Iter 26/500 - Loss: 0.166
Iter 27/500 - Loss: 0.121
Iter 28/500 - Loss: 0.077
Iter 29/500 - Loss: 0.033
Iter 30/500 - Loss: -0.009
Iter 31/500 - Loss: -0.051
Iter 32/500 - Loss: -0.092
Iter 33/500 - Loss: -0.132
Iter 34/500 - Loss: -0.172
Iter 35/500 - Loss: -0.210
Iter 36/500 - Loss: -0.248
Iter 37/500 - Loss: -0.285
Iter 38/500 - Loss: -0.321
Iter 39/50

Iter 403/500 - Loss: -1.780
Iter 404/500 - Loss: -1.782
Iter 405/500 - Loss: -1.781
Iter 406/500 - Loss: -1.782
Iter 407/500 - Loss: -1.784
Iter 408/500 - Loss: -1.784
Iter 409/500 - Loss: -1.785
Iter 410/500 - Loss: -1.785
Iter 411/500 - Loss: -1.785
Iter 412/500 - Loss: -1.786
Iter 413/500 - Loss: -1.787
Iter 414/500 - Loss: -1.786
Iter 415/500 - Loss: -1.788
Iter 416/500 - Loss: -1.789
Iter 417/500 - Loss: -1.788
Iter 418/500 - Loss: -1.789
Iter 419/500 - Loss: -1.789
Iter 420/500 - Loss: -1.790
Iter 421/500 - Loss: -1.790
Iter 422/500 - Loss: -1.791
Iter 423/500 - Loss: -1.791
Iter 424/500 - Loss: -1.793
Iter 425/500 - Loss: -1.793
Iter 426/500 - Loss: -1.793
Iter 427/500 - Loss: -1.793
Iter 428/500 - Loss: -1.794
Iter 429/500 - Loss: -1.795
Iter 430/500 - Loss: -1.796
Iter 431/500 - Loss: -1.795
Iter 432/500 - Loss: -1.796
Iter 433/500 - Loss: -1.797
Iter 434/500 - Loss: -1.796
Iter 435/500 - Loss: -1.797
Iter 436/500 - Loss: -1.798
Iter 437/500 - Loss: -1.799
Iter 438/500 - Loss:

Iter 308/500 - Loss: -1.191
Iter 309/500 - Loss: -1.190
Iter 310/500 - Loss: -1.192
Iter 311/500 - Loss: -1.191
Iter 312/500 - Loss: -1.191
Iter 313/500 - Loss: -1.192
Iter 314/500 - Loss: -1.193
Iter 315/500 - Loss: -1.192
Iter 316/500 - Loss: -1.194
Iter 317/500 - Loss: -1.194
Iter 318/500 - Loss: -1.195
Iter 319/500 - Loss: -1.196
Iter 320/500 - Loss: -1.196
Iter 321/500 - Loss: -1.195
Iter 322/500 - Loss: -1.196
Iter 323/500 - Loss: -1.196
Iter 324/500 - Loss: -1.197
Iter 325/500 - Loss: -1.197
Iter 326/500 - Loss: -1.198
Iter 327/500 - Loss: -1.197
Iter 328/500 - Loss: -1.199
Iter 329/500 - Loss: -1.199
Iter 330/500 - Loss: -1.200
Iter 331/500 - Loss: -1.199
Iter 332/500 - Loss: -1.200
Iter 333/500 - Loss: -1.200
Iter 334/500 - Loss: -1.200
Iter 335/500 - Loss: -1.201
Iter 336/500 - Loss: -1.201
Iter 337/500 - Loss: -1.201
Iter 338/500 - Loss: -1.201
Iter 339/500 - Loss: -1.202
Iter 340/500 - Loss: -1.202
Iter 341/500 - Loss: -1.203
Iter 342/500 - Loss: -1.203
Iter 343/500 - Loss:

In [3]:
X_train, X_test, y_train, y_test = train_test_split(
                X1.float(),
                Y1.float(),
                test_size=0.1,
                random_state=seed
            )

In [4]:
def proxy(a,y_train,m0,output):
    a=torch.tensor(a)
    res = ((a*m0-y_train)**2).mean(axis=1).detach().numpy()
    return res[output]

In [5]:
m=40
n=180
a=np.random.choice(range(X0.shape[0]),n,replace=False)
b=np.random.choice(range(X_train.shape[0]),m,replace=False)


emulator_0 = GPE.ensemble(X0[a,:],Y0[a,:],mean_func="linear",training_iter=500)
emulator_1 = GPE.ensemble(X_train[b,:],y_train[b,:],mean_func="linear",training_iter=500)
m0 = emulator_0.predict(X_train[b,:])

a_d=np.zeros(y_train.shape[1])
for l in range(y_train.shape[1]):
    result = scipy.optimize.minimize(proxy, 1, args=(y_train[b,:],m0,l), method='Nelder-Mead', tol=1e-8)
    print(result.x)
    a_d[l]=result.x

a_d=torch.tensor(a_d)
print(a_d)


m0 = emulator_0.predict(X_train[b,:])
y_adjust = torch.tensor(y_train[b] - a_d*m0)
delta_1 = GPE.ensemble(X_train[b,:],y_adjust,mean_func="linear",training_iter=500)
MSE_a = ((a_d*emulator_0.predict(X_test)+delta_1.predict(X_test)-torch.tensor(y_test))**2).mean(axis=0).detach().numpy()
R2_a = (1-((a_d*emulator_0.predict(X_test)+delta_1.predict(X_test)-torch.tensor(y_test))**2).mean(axis=0)/torch.tensor(y_test.var(axis=0))).detach().numpy()


0
Iter 1/500 - Loss: 3.353
Iter 2/500 - Loss: 2.809
Iter 3/500 - Loss: 2.398
Iter 4/500 - Loss: 2.095
Iter 5/500 - Loss: 1.874
Iter 6/500 - Loss: 1.714
Iter 7/500 - Loss: 1.597
Iter 8/500 - Loss: 1.509
Iter 9/500 - Loss: 1.443
Iter 10/500 - Loss: 1.390
Iter 11/500 - Loss: 1.347
Iter 12/500 - Loss: 1.310
Iter 13/500 - Loss: 1.278
Iter 14/500 - Loss: 1.249
Iter 15/500 - Loss: 1.221
Iter 16/500 - Loss: 1.194
Iter 17/500 - Loss: 1.167
Iter 18/500 - Loss: 1.140
Iter 19/500 - Loss: 1.112
Iter 20/500 - Loss: 1.084
Iter 21/500 - Loss: 1.055
Iter 22/500 - Loss: 1.025
Iter 23/500 - Loss: 0.994
Iter 24/500 - Loss: 0.961
Iter 25/500 - Loss: 0.928
Iter 26/500 - Loss: 0.893
Iter 27/500 - Loss: 0.858
Iter 28/500 - Loss: 0.821
Iter 29/500 - Loss: 0.783
Iter 30/500 - Loss: 0.744
Iter 31/500 - Loss: 0.704
Iter 32/500 - Loss: 0.663
Iter 33/500 - Loss: 0.622
Iter 34/500 - Loss: 0.579
Iter 35/500 - Loss: 0.536
Iter 36/500 - Loss: 0.492
Iter 37/500 - Loss: 0.448
Iter 38/500 - Loss: 0.404
Iter 39/500 - Loss:

Iter 393/500 - Loss: -1.963
Iter 394/500 - Loss: -1.964
Iter 395/500 - Loss: -1.964
Iter 396/500 - Loss: -1.964
Iter 397/500 - Loss: -1.965
Iter 398/500 - Loss: -1.965
Iter 399/500 - Loss: -1.966
Iter 400/500 - Loss: -1.966
Iter 401/500 - Loss: -1.967
Iter 402/500 - Loss: -1.968
Iter 403/500 - Loss: -1.968
Iter 404/500 - Loss: -1.968
Iter 405/500 - Loss: -1.969
Iter 406/500 - Loss: -1.970
Iter 407/500 - Loss: -1.970
Iter 408/500 - Loss: -1.971
Iter 409/500 - Loss: -1.971
Iter 410/500 - Loss: -1.972
Iter 411/500 - Loss: -1.972
Iter 412/500 - Loss: -1.973
Iter 413/500 - Loss: -1.973
Iter 414/500 - Loss: -1.974
Iter 415/500 - Loss: -1.974
Iter 416/500 - Loss: -1.975
Iter 417/500 - Loss: -1.975
Iter 418/500 - Loss: -1.976
Iter 419/500 - Loss: -1.976
Iter 420/500 - Loss: -1.977
Iter 421/500 - Loss: -1.977
Iter 422/500 - Loss: -1.978
Iter 423/500 - Loss: -1.978
Iter 424/500 - Loss: -1.979
Iter 425/500 - Loss: -1.979
Iter 426/500 - Loss: -1.979
Iter 427/500 - Loss: -1.980
Iter 428/500 - Loss:

Iter 256/500 - Loss: -1.375
Iter 257/500 - Loss: -1.375
Iter 258/500 - Loss: -1.376
Iter 259/500 - Loss: -1.376
Iter 260/500 - Loss: -1.377
Iter 261/500 - Loss: -1.377
Iter 262/500 - Loss: -1.378
Iter 263/500 - Loss: -1.378
Iter 264/500 - Loss: -1.379
Iter 265/500 - Loss: -1.380
Iter 266/500 - Loss: -1.380
Iter 267/500 - Loss: -1.380
Iter 268/500 - Loss: -1.381
Iter 269/500 - Loss: -1.381
Iter 270/500 - Loss: -1.382
Iter 271/500 - Loss: -1.383
Iter 272/500 - Loss: -1.383
Iter 273/500 - Loss: -1.383
Iter 274/500 - Loss: -1.384
Iter 275/500 - Loss: -1.384
Iter 276/500 - Loss: -1.385
Iter 277/500 - Loss: -1.385
Iter 278/500 - Loss: -1.386
Iter 279/500 - Loss: -1.386
Iter 280/500 - Loss: -1.387
Iter 281/500 - Loss: -1.387
Iter 282/500 - Loss: -1.388
Iter 283/500 - Loss: -1.388
Iter 284/500 - Loss: -1.389
Iter 285/500 - Loss: -1.389
Iter 286/500 - Loss: -1.389
Iter 287/500 - Loss: -1.390
Iter 288/500 - Loss: -1.390
Iter 289/500 - Loss: -1.391
Iter 290/500 - Loss: -1.391
Iter 291/500 - Loss:

Iter 210/500 - Loss: -0.685
Iter 211/500 - Loss: -0.686
Iter 212/500 - Loss: -0.686
Iter 213/500 - Loss: -0.686
Iter 214/500 - Loss: -0.687
Iter 215/500 - Loss: -0.687
Iter 216/500 - Loss: -0.688
Iter 217/500 - Loss: -0.688
Iter 218/500 - Loss: -0.689
Iter 219/500 - Loss: -0.689
Iter 220/500 - Loss: -0.690
Iter 221/500 - Loss: -0.690
Iter 222/500 - Loss: -0.690
Iter 223/500 - Loss: -0.691
Iter 224/500 - Loss: -0.691
Iter 225/500 - Loss: -0.691
Iter 226/500 - Loss: -0.690
Iter 227/500 - Loss: -0.687
Iter 228/500 - Loss: -0.680
Iter 229/500 - Loss: -0.672
Iter 230/500 - Loss: -0.674
Iter 231/500 - Loss: -0.690
Iter 232/500 - Loss: -0.692
Iter 233/500 - Loss: -0.682
Iter 234/500 - Loss: -0.688
Iter 235/500 - Loss: -0.695
Iter 236/500 - Loss: -0.688
Iter 237/500 - Loss: -0.690
Iter 238/500 - Loss: -0.696
Iter 239/500 - Loss: -0.691
Iter 240/500 - Loss: -0.693
Iter 241/500 - Loss: -0.697
Iter 242/500 - Loss: -0.693
Iter 243/500 - Loss: -0.695
Iter 244/500 - Loss: -0.698
Iter 245/500 - Loss:

Iter 89/500 - Loss: 0.053
Iter 90/500 - Loss: 0.038
Iter 91/500 - Loss: 0.023
Iter 92/500 - Loss: 0.008
Iter 93/500 - Loss: -0.006
Iter 94/500 - Loss: -0.019
Iter 95/500 - Loss: -0.033
Iter 96/500 - Loss: -0.046
Iter 97/500 - Loss: -0.060
Iter 98/500 - Loss: -0.073
Iter 99/500 - Loss: -0.086
Iter 100/500 - Loss: -0.100
Iter 101/500 - Loss: -0.113
Iter 102/500 - Loss: -0.126
Iter 103/500 - Loss: -0.139
Iter 104/500 - Loss: -0.152
Iter 105/500 - Loss: -0.165
Iter 106/500 - Loss: -0.177
Iter 107/500 - Loss: -0.189
Iter 108/500 - Loss: -0.201
Iter 109/500 - Loss: -0.213
Iter 110/500 - Loss: -0.224
Iter 111/500 - Loss: -0.235
Iter 112/500 - Loss: -0.246
Iter 113/500 - Loss: -0.256
Iter 114/500 - Loss: -0.267
Iter 115/500 - Loss: -0.277
Iter 116/500 - Loss: -0.288
Iter 117/500 - Loss: -0.304
Iter 118/500 - Loss: -0.315
Iter 119/500 - Loss: -0.332
Iter 120/500 - Loss: -0.345
Iter 121/500 - Loss: -0.361
Iter 122/500 - Loss: -0.375
Iter 123/500 - Loss: -0.389
Iter 124/500 - Loss: -0.402
Iter 12

Iter 479/500 - Loss: -0.849
Iter 480/500 - Loss: -0.849
Iter 481/500 - Loss: -0.849
Iter 482/500 - Loss: -0.850
Iter 483/500 - Loss: -0.850
Iter 484/500 - Loss: -0.850
Iter 485/500 - Loss: -0.850
Iter 486/500 - Loss: -0.850
Iter 487/500 - Loss: -0.850
Iter 488/500 - Loss: -0.850
Iter 489/500 - Loss: -0.851
Iter 490/500 - Loss: -0.851
Iter 491/500 - Loss: -0.851
Iter 492/500 - Loss: -0.851
Iter 493/500 - Loss: -0.851
Iter 494/500 - Loss: -0.851
Iter 495/500 - Loss: -0.851
Iter 496/500 - Loss: -0.851
Iter 497/500 - Loss: -0.852
Iter 498/500 - Loss: -0.852
Iter 499/500 - Loss: -0.852
Iter 500/500 - Loss: -0.852
[0.80837509]
[0.87874504]
tensor([0.8084, 0.8787], dtype=torch.float64)
0
Iter 1/500 - Loss: 2.390
Iter 2/500 - Loss: 2.012
Iter 3/500 - Loss: 1.756
Iter 4/500 - Loss: 1.587
Iter 5/500 - Loss: 1.478
Iter 6/500 - Loss: 1.412
Iter 7/500 - Loss: 1.373
Iter 8/500 - Loss: 1.351
Iter 9/500 - Loss: 1.338
Iter 10/500 - Loss: 1.328
Iter 11/500 - Loss: 1.317
Iter 12/500 - Loss: 1.303
Iter 13

/var/folders/_j/ptyc01811q5b1dg30hshtfzh0000gr/T/ipykernel_18812/1166754089.py:22: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_adjust = torch.tensor(y_train[b] - a_d*m0)


Iter 157/500 - Loss: 0.334
Iter 158/500 - Loss: 0.334
Iter 159/500 - Loss: 0.333
Iter 160/500 - Loss: 0.333
Iter 161/500 - Loss: 0.333
Iter 162/500 - Loss: 0.332
Iter 163/500 - Loss: 0.332
Iter 164/500 - Loss: 0.332
Iter 165/500 - Loss: 0.331
Iter 166/500 - Loss: 0.331
Iter 167/500 - Loss: 0.330
Iter 168/500 - Loss: 0.330
Iter 169/500 - Loss: 0.330
Iter 170/500 - Loss: 0.329
Iter 171/500 - Loss: 0.329
Iter 172/500 - Loss: 0.329
Iter 173/500 - Loss: 0.328
Iter 174/500 - Loss: 0.328
Iter 175/500 - Loss: 0.328
Iter 176/500 - Loss: 0.327
Iter 177/500 - Loss: 0.327
Iter 178/500 - Loss: 0.327
Iter 179/500 - Loss: 0.326
Iter 180/500 - Loss: 0.326
Iter 181/500 - Loss: 0.326
Iter 182/500 - Loss: 0.326
Iter 183/500 - Loss: 0.325
Iter 184/500 - Loss: 0.325
Iter 185/500 - Loss: 0.325
Iter 186/500 - Loss: 0.324
Iter 187/500 - Loss: 0.324
Iter 188/500 - Loss: 0.324
Iter 189/500 - Loss: 0.324
Iter 190/500 - Loss: 0.324
Iter 191/500 - Loss: 0.323
Iter 192/500 - Loss: 0.323
Iter 193/500 - Loss: 0.322
I

Iter 33/500 - Loss: 0.700
Iter 34/500 - Loss: 0.663
Iter 35/500 - Loss: 0.625
Iter 36/500 - Loss: 0.588
Iter 37/500 - Loss: 0.551
Iter 38/500 - Loss: 0.513
Iter 39/500 - Loss: 0.475
Iter 40/500 - Loss: 0.436
Iter 41/500 - Loss: 0.398
Iter 42/500 - Loss: 0.361
Iter 43/500 - Loss: 0.325
Iter 44/500 - Loss: 0.292
Iter 45/500 - Loss: 0.262
Iter 46/500 - Loss: 0.236
Iter 47/500 - Loss: 0.213
Iter 48/500 - Loss: 0.193
Iter 49/500 - Loss: 0.176
Iter 50/500 - Loss: 0.162
Iter 51/500 - Loss: 0.150
Iter 52/500 - Loss: 0.142
Iter 53/500 - Loss: 0.136
Iter 54/500 - Loss: 0.132
Iter 55/500 - Loss: 0.130
Iter 56/500 - Loss: 0.129
Iter 57/500 - Loss: 0.127
Iter 58/500 - Loss: 0.124
Iter 59/500 - Loss: 0.120
Iter 60/500 - Loss: 0.115
Iter 61/500 - Loss: 0.108
Iter 62/500 - Loss: 0.101
Iter 63/500 - Loss: 0.090
Iter 64/500 - Loss: 0.077
Iter 65/500 - Loss: 0.062
Iter 66/500 - Loss: 0.047
Iter 67/500 - Loss: 0.032
Iter 68/500 - Loss: 0.017
Iter 69/500 - Loss: 0.003
Iter 70/500 - Loss: -0.010
Iter 71/500

Iter 423/500 - Loss: -0.374
Iter 424/500 - Loss: -0.374
Iter 425/500 - Loss: -0.374
Iter 426/500 - Loss: -0.374
Iter 427/500 - Loss: -0.374
Iter 428/500 - Loss: -0.374
Iter 429/500 - Loss: -0.374
Iter 430/500 - Loss: -0.373
Iter 431/500 - Loss: -0.372
Iter 432/500 - Loss: -0.370
Iter 433/500 - Loss: -0.367
Iter 434/500 - Loss: -0.362
Iter 435/500 - Loss: -0.355
Iter 436/500 - Loss: -0.351
Iter 437/500 - Loss: -0.355
Iter 438/500 - Loss: -0.367
Iter 439/500 - Loss: -0.374
Iter 440/500 - Loss: -0.371
Iter 441/500 - Loss: -0.363
Iter 442/500 - Loss: -0.361
Iter 443/500 - Loss: -0.367
Iter 444/500 - Loss: -0.374
Iter 445/500 - Loss: -0.375
Iter 446/500 - Loss: -0.370
Iter 447/500 - Loss: -0.368
Iter 448/500 - Loss: -0.371
Iter 449/500 - Loss: -0.375
Iter 450/500 - Loss: -0.375
Iter 451/500 - Loss: -0.373
Iter 452/500 - Loss: -0.371
Iter 453/500 - Loss: -0.372
Iter 454/500 - Loss: -0.375
Iter 455/500 - Loss: -0.376
Iter 456/500 - Loss: -0.375
Iter 457/500 - Loss: -0.373
Iter 458/500 - Loss:

/var/folders/_j/ptyc01811q5b1dg30hshtfzh0000gr/T/ipykernel_18812/1166754089.py:24: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  MSE_a = ((a_d*emulator_0.predict(X_test)+delta_1.predict(X_test)-torch.tensor(y_test))**2).mean(axis=0).detach().numpy()
/var/folders/_j/ptyc01811q5b1dg30hshtfzh0000gr/T/ipykernel_18812/1166754089.py:25: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  R2_a = (1-((a_d*emulator_0.predict(X_test)+delta_1.predict(X_test)-torch.tensor(y_test))**2).mean(axis=0)/torch.tensor(y_test.var(axis=0))).detach().numpy()


In [6]:
MSE_a

array([3.29899966, 2.6291519 ])

In [7]:
R2_a

array([0.99899495, 0.9955174 ])

In [8]:
emulator_0.models[0].mean_module.bias

Parameter containing:
tensor([1.8997], requires_grad=True)

In [9]:
ref_weights=emulator_0.models[0].mean_module.weights
ref_bias = emulator_0.models[0].mean_module.bias

In [10]:
ref_outputscale=emulator_0.models[0].covar_module.outputscale*a[0]**2

In [11]:
model_d = GPE.ensemble(X_train[b,:],y_train[b,:],mean_func="discrepancy",training_iter=500,ref_emulator=emulator_0,a=a_d)

0
Iter 1/500 - Loss: 4.217
Iter 2/500 - Loss: 3.593
Iter 3/500 - Loss: 3.087
Iter 4/500 - Loss: 2.684
Iter 5/500 - Loss: 2.370
Iter 6/500 - Loss: 2.129
Iter 7/500 - Loss: 1.949
Iter 8/500 - Loss: 1.815
Iter 9/500 - Loss: 1.717
Iter 10/500 - Loss: 1.646
Iter 11/500 - Loss: 1.594
Iter 12/500 - Loss: 1.556
Iter 13/500 - Loss: 1.528
Iter 14/500 - Loss: 1.506
Iter 15/500 - Loss: 1.489
Iter 16/500 - Loss: 1.473
Iter 17/500 - Loss: 1.459
Iter 18/500 - Loss: 1.445
Iter 19/500 - Loss: 1.431
Iter 20/500 - Loss: 1.416
Iter 21/500 - Loss: 1.401
Iter 22/500 - Loss: 1.384
Iter 23/500 - Loss: 1.367
Iter 24/500 - Loss: 1.348
Iter 25/500 - Loss: 1.329
Iter 26/500 - Loss: 1.308
Iter 27/500 - Loss: 1.287
Iter 28/500 - Loss: 1.266
Iter 29/500 - Loss: 1.243
Iter 30/500 - Loss: 1.221
Iter 31/500 - Loss: 1.198
Iter 32/500 - Loss: 1.174
Iter 33/500 - Loss: 1.151
Iter 34/500 - Loss: 1.127
Iter 35/500 - Loss: 1.103
Iter 36/500 - Loss: 1.079
Iter 37/500 - Loss: 1.055
Iter 38/500 - Loss: 1.030
Iter 39/500 - Loss:

Iter 304/500 - Loss: -0.663
Iter 305/500 - Loss: -0.664
Iter 306/500 - Loss: -0.663
Iter 307/500 - Loss: -0.664
Iter 308/500 - Loss: -0.665
Iter 309/500 - Loss: -0.665
Iter 310/500 - Loss: -0.665
Iter 311/500 - Loss: -0.665
Iter 312/500 - Loss: -0.666
Iter 313/500 - Loss: -0.666
Iter 314/500 - Loss: -0.666
Iter 315/500 - Loss: -0.666
Iter 316/500 - Loss: -0.667
Iter 317/500 - Loss: -0.667
Iter 318/500 - Loss: -0.668
Iter 319/500 - Loss: -0.668
Iter 320/500 - Loss: -0.668
Iter 321/500 - Loss: -0.668
Iter 322/500 - Loss: -0.669
Iter 323/500 - Loss: -0.669
Iter 324/500 - Loss: -0.669
Iter 325/500 - Loss: -0.670
Iter 326/500 - Loss: -0.670
Iter 327/500 - Loss: -0.670
Iter 328/500 - Loss: -0.670
Iter 329/500 - Loss: -0.671
Iter 330/500 - Loss: -0.671
Iter 331/500 - Loss: -0.671
Iter 332/500 - Loss: -0.672
Iter 333/500 - Loss: -0.672
Iter 334/500 - Loss: -0.672
Iter 335/500 - Loss: -0.672
Iter 336/500 - Loss: -0.673
Iter 337/500 - Loss: -0.673
Iter 338/500 - Loss: -0.673
Iter 339/500 - Loss:

Iter 109/500 - Loss: -0.683
Iter 110/500 - Loss: -0.687
Iter 111/500 - Loss: -0.690
Iter 112/500 - Loss: -0.695
Iter 113/500 - Loss: -0.699
Iter 114/500 - Loss: -0.703
Iter 115/500 - Loss: -0.706
Iter 116/500 - Loss: -0.710
Iter 117/500 - Loss: -0.713
Iter 118/500 - Loss: -0.716
Iter 119/500 - Loss: -0.719
Iter 120/500 - Loss: -0.722
Iter 121/500 - Loss: -0.725
Iter 122/500 - Loss: -0.728
Iter 123/500 - Loss: -0.730
Iter 124/500 - Loss: -0.733
Iter 125/500 - Loss: -0.735
Iter 126/500 - Loss: -0.738
Iter 127/500 - Loss: -0.740
Iter 128/500 - Loss: -0.743
Iter 129/500 - Loss: -0.745
Iter 130/500 - Loss: -0.747
Iter 131/500 - Loss: -0.749
Iter 132/500 - Loss: -0.751
Iter 133/500 - Loss: -0.753
Iter 134/500 - Loss: -0.755
Iter 135/500 - Loss: -0.757
Iter 136/500 - Loss: -0.758
Iter 137/500 - Loss: -0.759
Iter 138/500 - Loss: -0.760
Iter 139/500 - Loss: -0.761
Iter 140/500 - Loss: -0.761
Iter 141/500 - Loss: -0.764
Iter 142/500 - Loss: -0.767
Iter 143/500 - Loss: -0.770
Iter 144/500 - Loss:

Iter 423/500 - Loss: -0.867
Iter 424/500 - Loss: -0.863
Iter 425/500 - Loss: -0.861
Iter 426/500 - Loss: -0.865
Iter 427/500 - Loss: -0.871
Iter 428/500 - Loss: -0.874
Iter 429/500 - Loss: -0.872
Iter 430/500 - Loss: -0.870
Iter 431/500 - Loss: -0.873
Iter 432/500 - Loss: -0.875
Iter 433/500 - Loss: -0.875
Iter 434/500 - Loss: -0.873
Iter 435/500 - Loss: -0.874
Iter 436/500 - Loss: -0.877
Iter 437/500 - Loss: -0.877
Iter 438/500 - Loss: -0.875
Iter 439/500 - Loss: -0.875
Iter 440/500 - Loss: -0.877
Iter 441/500 - Loss: -0.878
Iter 442/500 - Loss: -0.877
Iter 443/500 - Loss: -0.876
Iter 444/500 - Loss: -0.877
Iter 445/500 - Loss: -0.878
Iter 446/500 - Loss: -0.878
Iter 447/500 - Loss: -0.877
Iter 448/500 - Loss: -0.878
Iter 449/500 - Loss: -0.878
Iter 450/500 - Loss: -0.879
Iter 451/500 - Loss: -0.879
Iter 452/500 - Loss: -0.879
Iter 453/500 - Loss: -0.879
Iter 454/500 - Loss: -0.879
Iter 455/500 - Loss: -0.880
Iter 456/500 - Loss: -0.880
Iter 457/500 - Loss: -0.880
Iter 458/500 - Loss:

In [12]:
a_d

tensor([0.8084, 0.8787], dtype=torch.float64)

In [13]:
emulator_0.models[0].covar_module.lengthscale

In [14]:
emulator_1.MSE(X_test,y_test)

tensor([5.9113, 3.6331], grad_fn=<MeanBackward1>)

In [15]:
ref_lengthscale=emulator_0.models[0].covar_module.base_kernel.lengthscale

In [16]:
emulator_1.R2(X_test,y_test)

/Users/pmzcwl/Documents/GitHub/Calibration/GPE_ensemble.py:205: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  R2_score=1-self.MSE(inputVals,outputVals)/torch.tensor(torch.var(outputVals,axis=0))


tensor([0.9982, 0.9938], grad_fn=<RsubBackward1>)

In [17]:
emulator_0.models[0].covar_module.base_kernel.lengthscale

tensor([[18.4432, 17.3852, 22.5404,  1.3815,  6.6191,  1.5393]],
       grad_fn=<SoftplusBackward0>)

In [18]:
model_d.MSE(X_test,y_test)

tensor([6.4398, 3.6812], grad_fn=<MeanBackward1>)

In [19]:
model_d.R2(X_test,y_test)

tensor([0.9980, 0.9937], grad_fn=<RsubBackward1>)

In [20]:
model_d.models[0].covar_module.kernels[0].kernels[0].base_kernel.lengthscale

tensor([[18.4432, 17.3852, 22.5404,  1.3815,  6.6191,  1.5393]])

In [21]:
emulator_0.models[0].covar_module.base_kernel.lengthscale

tensor([[18.4432, 17.3852, 22.5404,  1.3815,  6.6191,  1.5393]],
       grad_fn=<SoftplusBackward0>)

In [22]:
model_d.models[0].covar_module.kernels[0].kernels[0].outputscale

tensor(0.5819)

In [23]:
emulator_0.models[0].covar_module.outputscale

tensor(0.5819, grad_fn=<SoftplusBackward0>)

In [24]:
a_d

tensor([0.8084, 0.8787], dtype=torch.float64)

In [25]:
[model_d.models[0].a,model_d.models[1].a]

[tensor(0.8084, dtype=torch.float64), tensor(0.8787, dtype=torch.float64)]

In [26]:
for param_name, param in model_d.models[0].named_parameters():
    print(param_name)

likelihood.noise_covar.raw_noise
mean_module.weights
mean_module.bias
mean_module.ref_weights
mean_module.ref_bias
covar_module.kernels.0.kernels.0.raw_outputscale
covar_module.kernels.0.kernels.0.base_kernel.raw_lengthscale
covar_module.kernels.1.raw_outputscale
covar_module.kernels.1.base_kernel.raw_lengthscale


In [27]:
for param_name, param in model_d.models[0].named_parameters():
    print(param)

Parameter containing:
tensor([-9.4347], requires_grad=True)
Parameter containing:
tensor([[-0.0042],
        [ 0.0114],
        [-0.0014],
        [ 0.1727],
        [ 0.0058],
        [ 0.0833]], requires_grad=True)
Parameter containing:
tensor([-0.7015], requires_grad=True)
Parameter containing:
tensor([[ 2.2202e-03],
        [-7.7364e-03],
        [ 1.5555e-03],
        [-1.6636e+00],
        [-2.2457e-01],
        [-5.2257e-01]])
Parameter containing:
tensor([1.8131])
Parameter containing:
tensor(-0.3044)
Parameter containing:
tensor([[17.9790, 17.1830, 18.2233,  1.0834,  6.5503,  1.2848]])
Parameter containing:
tensor(-1.3593, requires_grad=True)
Parameter containing:
tensor([[22.3640, 17.6016, 19.1037,  0.7153,  4.2949,  2.2952]],
       requires_grad=True)


In [28]:
emulator_0.models[0].mean_module.bias

Parameter containing:
tensor([1.8131])

In [29]:
#b=np.random.choice(range(X_train.shape[0]),18,replace=False)
p = int(X0.shape[0]*0.05)
n = int(X0.shape[0]/p)
m = 18
MSE_mn = np.zeros((n,m,2))
R2_mn = np.zeros((n,m,2))
reps = 5
for i in range(n):
    for k in range(m):
        for j in range(reps):
            b=np.random.choice(range(X_train.shape[0]),(k+1)*p,replace=False)
            a=np.random.choice(range(X0.shape[0]),(i+1)*p,replace=False)
            emulator_0 = GPE.ensemble(X0[a,:],Y0[a,:],mean_func="linear",training_iter=500)
            delta_1 = GPE.ensemble(X_train[b,:],y_train[b,:],mean_func="discrepancy",training_iter=500,ref_emulator=emulator_0,a=a_d)
            MSE_mn[i,k] += delta_1.MSE(X_test,y_test).detach().numpy()/reps
            R2_mn[i,k] += delta_1.R2(X_test,y_test).detach().numpy()/reps


0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1


KeyboardInterrupt: 

In [ ]:
x = np.linspace(9,162,18)

y = np.linspace(9,180,20)

xx,yy=np.meshgrid(x,y)

xx[1:,1:].shape

level = 1

plt.contourf(xx[level:,level:],yy[level:,level:],R2_mn[level:,level:,0],origin='lower',levels=50)
plt.ylabel('n')
plt.xlabel('m')
plt.colorbar()

In [ ]:
class DiscrepancyMean(gpytorch.means.Mean):
    def __init__(self, input_size, batch_shape=torch.Size(), bias=True,ref_weights=0,ref_bias=0,a=0):
        super().__init__()
        self.register_parameter(name="weights", parameter=torch.nn.Parameter(torch.randn(*batch_shape, input_size, 1)))
        if bias:
            self.register_parameter(name="bias", parameter=torch.nn.Parameter(torch.randn(*batch_shape, 1)))
        else:
            self.bias = None
        self.a=a
    def forward(self, x):
        ref = x.matmul(ref_weights).squeeze(-1)
        res = x.matmul(self.weights).squeeze(-1)
        if self.bias is not None:
            res = self.a*(ref+ref_bias)+res + self.bias
        return res


In [ ]:
class ExactGPModel(gpytorch.models.ExactGP):
    def __init__(self, train_x, train_y, likelihood):
        super(ExactGPModel, self).__init__(train_x, train_y, likelihood)
        nDim = train_x.shape[1]
        self.mean_module = DiscrepancyMean(input_size=nDim,ref_weights=ref_weights,ref_bias=ref_bias,a=a_d[0])
        self.covar_module = gpytorch.kernels.ScaleKernel(gpytorch.kernels.RBFKernel(ard_num_dims=nDim,lengthscale=ref_lengthscale),outputscale=ref_outputscale)+gpytorch.kernels.ScaleKernel(gpytorch.kernels.RBFKernel(ard_num_dims=nDim))

    def forward(self, x):
        mean_x = self.mean_module(x)
        covar_x = self.covar_module(x)
        return gpytorch.distributions.MultivariateNormal(mean_x, covar_x)

In [ ]:
ref_weights=emulator_0.models[0].mean_module.weights
ref_bias = emulator_0.models[0].mean_module.bias

In [ ]:
# Wrap training, prediction and plotting from the ExactGP-Tutorial into a function,
# so that we do not have to repeat the code later on
def train(model, likelihood,train_x,train_y, training_iter=500):
    # Use the adam optimizer
    optimizer = torch.optim.Adam(model.parameters(), lr=0.1)  # Includes GaussianLikelihood parameters

    # "Loss" for GPs - the marginal log likelihood
    mll = gpytorch.mlls.ExactMarginalLogLikelihood(likelihood, model)

    for i in range(training_iter):
        # Zero gradients from previous iteration
        optimizer.zero_grad()
        # Output from model
        output = model(train_x)
        # Calc loss and backprop gradients
        loss = -mll(output, train_y)
        loss.backward()
        optimizer.step()


def predict(model, likelihood, test_x = torch.linspace(0, 1, 51)):
    model.eval()
    likelihood.eval()
    # Make predictions by feeding model through likelihood
    with torch.no_grad(), gpytorch.settings.fast_pred_var():
        # Test points are regularly spaced along [0,1]
        return likelihood(model(test_x))

In [ ]:
likelihood = gpytorch.likelihoods.GaussianLikelihood()
model = ExactGPModel(X_train, y_train[:,0], likelihood)

In [ ]:
model.train()
likelihood.train()
train(model, likelihood,X_train,y_train[:,0])

In [ ]:
1-((predict(model,likelihood,test_x=X_test).mean-y_test[:,0])**2).mean()/y_test.var()

In [ ]:
a_d